#! /usr/bin/env python
"""
Take a pickle file of the sort generated by makeRosterFromCanvas.py containing
a list with names, and create a randomly generated set of groups from those
names. Takes as command-line arguments the file containing the names, and the number of groups to
generate. Prints the groups of names to standard out.
"""

import pickle, random, sys

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print('Usage: makeGroups name_file number_of_groups')
        sys.exit(1)

    try:
        num_groups = int(sys.argv[2])
    except:
        print('Usage: makeGroups name_file number_of_groups')
        print('number of groups must be integers')
        sys.exit(1)

    fin = open(sys.argv[1], 'rb')
    name_l = pickle.load(fin)
    fin.close()

    random.shuffle(name_l)
    out_list = []
    for i in range(0, num_groups):
        out_list.append([])

    i = 0
    for n in name_l:
        out_list[i].append(n)
        i = (i + 1) % num_groups

    for i in range(0, num_groups):
        print(', '.join(name for name in out_list[i]))
